services:
  eidolon-app:
    image: python:3.11-slim
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        pip install fastapi uvicorn openai python-dotenv &&
        python -c 'print(\"Eidolon AI Project Started!\")' &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: unless-stopped